### ISSUE TITLE
As a user, I want to see Simple Signer popups with a specific dimension

### ISSUE THREAD

**Issue by Genebson** [bigger-tech/simple-stellar-signer#135]
Background:

The only way to resize popups is when a client implements Simple Signer inside his project.
The objective of this ticket is to give Simple Signer a default size when it's opened.

**Comment by RivarolaNicolas** [comment]
Minimum size when signing a transaction:

![image](https://user-images.githubusercontent.com/56001809/167475886-a4500679-d3e8-416b-ba8e-655e197c8e86.png)

Minimum size when connecting:

![image](https://user-images.githubusercontent.com/56001809/167476141-77860709-e704-4c59-bdcf-991b7e5b97b0.png)
