### ISSUE TITLE
Not able to submit simple signer signed transaction to stellar network

### ISSUE THREAD

**Issue by SaadUlHassan** [bigger-tech/simple-stellar-signer#169]
I am signing my transactions via simple signer but when i submit the transaction, the api responds with following error:

```
{
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://developers.stellar.org/api/errors/http-status-codes/horizon-specific/transaction-failed/",
  "extras": {
    "envelope_xdr": "AAAAAgAAAAB/Nq6AY76iEii24IFkU2VDqBcqWdpiM9TWSPRyLuMSeAAPQkAAAY4gAAAAEgAAAAEAAAAAAAAAAAAAAABkIeFGAAAAAAAAAAEAAAAAAAAAAQAAAADAtWlHBYJA3iVLm7yBl7sw6X+SQl9JUxKoV5jZCGIiDAAAAAAAAAAAAJiWgAAAAAAAAAABCGIiDAAAAEBptL6X/1qWZ9J57sho0kfLdZ2CdisiVHzNWF37pa7EtJ3cuzQ3pq03Ehw8BdGc+q5feBxgRFRYDak2Dw+KkzgP",
    "result_codes": {
      "transaction": "tx_bad_auth"
    },
    "result_xdr": "AAAAAAAAAGT////6AAAAAA=="
  }
}
```

Here is the payload for the transactions API (https://horizon-testnet.stellar.org/transactions)

Payload:
`tx=AAAAAgAAAAB%2FNq6AY76iEii24IFkU2VDqBcqWdpiM9TWSPRyLuMSeAAPQkAAAY4gAAAAEgAAAAEAAAAAAAAAAAAAAABkIeFGAAAAAAAAAAEAAAAAAAAAAQAAAADAtWlHBYJA3iVLm7yBl7sw6X%2BSQl9JUxKoV5jZCGIiDAAAAAAAAAAAAJiWgAAAAAAAAAABCGIiDAAAAEBptL6X%2F1qWZ9J57sho0kfLdZ2CdisiVHzNWF37pa7EtJ3cuzQ3pq03Ehw8BdGc%2Bq5feBxgRFRYDak2Dw%2BKkzgP`

Please help me in this regard & let me know if you need anything else from me.

**Comment by SaadUlHassan** [comment]
@fsodano

**Comment by Ja-boop** [comment]
Thanks for letting us know, we will take a look

**Comment by Genebson** [comment]
Hey @SaadUlHassan 👋,

Have you signed the operation with your source account?
Cheers.

**Comment by SaadUlHassan** [comment]
> Hey @SaadUlHassan 👋,
> 
> Have you signed the operation with your source account? Cheers.

Hi,

So i have initiated the transaction, converted it to XDR and then submitted that to Stellar Network which got failed. Previously, i initiated the transaction, simply sign it and submit to Stellar Network which gets accepted but when integrating with simple signer it somehow failed.

**Comment by Genebson** [comment]
In the [lab](https://laboratory.stellar.org/#xdr-viewer?type=TransactionEnvelope&network=test), upon placing your XDR, you may observe that your transaction has been attempted to be signed with your destination account, whereas it should have been signed with your source account instead.

**Comment by SaadUlHassan** [comment]
![image](https://user-images.githubusercontent.com/41550402/228576361-9b506065-d0ac-40f3-acb1-a6c41e6dae14.png)

I have checked and this is the screenshot of Confirm a Transaction and we can see that the transaction is signed from source account but when it is sent to Stellar it fails.

**Comment by Genebson** [comment]
Have you checked your network? I think you're trying to sign the transaction on the public network but should be on the testnet.

![image](https://user-images.githubusercontent.com/65625400/228636920-e9bee523-b683-4f67-bd33-e479203a2ef9.png)

Try this: https://sign-test.plutodao.finance/

Btw, you should never pass your secret key through a query or render it in your UI.

**Comment by SaadUlHassan** [comment]
@Genebson 
Thank you for your suggestion. I tried the link you provided and it worked perfectly. It was indeed my mistake, as I was trying to sign the transaction on the public network instead of the testnet. I apologize for the confusion and thank you and your team for the prompt response to my Github issue.

**Comment by Genebson** [comment]
No worries @SaadUlHassan.

I'm going to close this issue as it's resolved.
