### ISSUE TITLE
Getting Error when opening Simple Signer Window

### ISSUE THREAD

**Issue by SaadUlHassan** [bigger-tech/simple-stellar-signer#170]
![image](https://user-images.githubusercontent.com/41550402/229309575-d94114bc-d21c-4efe-adf1-07fe443d17fe.png)

Hi,

I sometimes face this issue when i want to sign my transaction using simple signer. 
Before requesting & opening the window like this:

`window.open(`${getSimpleSignerHost(!!isPubnet)?.url}/sign`, 'Sign_Window', 'width=360, height=700');`

I am first checking if the xdrUnsigned is valid or not. If its valid only then i am requesting & opening the Simple Signer Window but still sometimes i get error that Sorry XDR wasn't provided.

I am validating xdrUnsigned using this code:

`const checkValidXDR = StellarSdk.xdr.TransactionEnvelope.validateXDR(transaction.toXDR(), 'base64'); `

Also sometimes i get the UI in Simple Signer window like User is not Connected. Then Go to Connect button is there.

Thanks.

**Comment by fsodano** [comment]
Hey mate, I recommend you read the docs once more. In this case you're not
passing the XDR to simple signer.

Here's an example (as per the docs) on how to do it:
https://github.com/PlutoDAO/simple-stellar-signer/blob/main/test.html

Cheers

**Comment by Genebson** [comment]
I'll proceed to close this issue since there has not been any recent activity. Please open a new issue if you think you have a related problem.
